### PR TITLE
update metadata

### PR DESCRIPTION
**Pull request by jeffrey-zang**
- upload logo.png to /public
- Add logo, title, and description metadata

### CODE REVIEW

**Review by Bad3r — CHANGES_REQUESTED** [review]
Please remove the yarn.lock file

**Comment by jeffrey-zang** [comment]
done @Bad3r

**Comment by Bad3r** [comment]
@jeffrey-zang thank you! this might be a good time to use fixups 

https://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html

**Comment by Bad3r** [comment]
[docs/package-lock.json](https://github.com/logseq/plugins/pull/5/files#diff-aced7929d69b779cb242efe99440d62fdf10cc24bb6ac6a958cb0870be3d41a0)

this will also need to be removed before merge

**Comment by jeffrey-zang** [comment]
@Bad3r that's my bad, thought it was gitignored 😅

**Comment by Bad3r** [comment]
> @Bad3r that's my bad, thought it was gitignored 😅

It should be lol

**Comment by jeffrey-zang** [comment]
Also since you guys use vercel shouldn't there be a preview deployment?

**Comment by Bad3r** [comment]
@jeffrey-zang we used GitHub pages for hosting. The website is deployed via github actions.
https://github.com/logseq/plugins/deployments

**Comment by jeffrey-zang** [comment]
@Bad3r ohhhh i see now, 
image
why is there a vercel logo then lol

**Pull request closed without merging**
